### ISSUE TITLE
incorrect work with SIMtraсe2

### ISSUE THREAD

**Issue by edbek** [tomasz-lisowski/swicc-drv-ifd#4]
I purchased a SIMtraсe2 in order to connect swsim with a real GSM modem.
But I get errors. I have a question: did you have any practice of using SIMtraсe2 ?

**Comment by tomasz-lisowski** [comment]
Yes, I tested swSIM with multiple phones using SIMtrace. If you list the errors you're getting, perhaps I'll be able to help.

**Comment by edbek** [comment]
When the real GSM modem starts with swsim, I don't see the modem accessing the EF_Kc. And most importantly, there is no authentication, that is, there is no command "A0 88 ..." from modem.

**Comment by tomasz-lisowski** [comment]
I closed a PR recently that fixed issues preventing some 2G devices from getting to authentication with swSIM, perhaps try with the updated version of swSIM? https://github.com/tomasz-lisowski/swsim/pull/9

**Comment by tomasz-lisowski** [comment]
Did you manage to solve your issue?

**Comment by edbek** [comment]
Yes, there were problems with the file system earlier, but I changed it now and everything worked.
I'm still testing swSIM with a real GSM modem and I'm noticing small inaccuracies in the work. When I finish my testing, I will post comments.
Thank you.
